[FIX] CD SSH

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -70,10 +70,11 @@ jobs:
           key: ${{ secrets.SERVER_SSH }} 
           script: |
             cd ~/Desktop/Airflow 
-
+            DOCKER="/Applications/Docker.app/Contents/Resources/bin/docker"
+            DOCKER_COMPOSE="/Applications/Docker.app/Contents/Resources/bin/docker-compose"
+            if [ -f "$DOCKER" ]; then echo "Docker Found"; else echo "Docker NOT Found at $DOCKER"; exit 1; fi
             echo "${{ secrets.GIT_HUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
             docker compose pull
             docker compose up -d
-
 
